return {
    Name = "Volcano ( Hard )",
    Difficulty = "dif_hard",
    MaxPlace = 20,
    UfoReserve = 0,
    DefaultAngle = {-math.pi, 0, -math.pi},
    DefaultRotation = 180,
    Price = {
        unit_cactus = 150,
        unit_palm_tree = 500,
        unit_scent_flower = 1250,
        unit_ufo = 1200,
    },
    Events = {
        {
            Type = "StartUpgradeAll",
            Name = "Upgrade_After5",
            RequireMinPlaced = 5,
            StopAtWave = 9,
        },
        {
            Type = "StartPlace",
            Name = "Place1_Fast_1to7",
            HardCap = 7,
            MaxCount = 7,
            SoftFail = false,
            MaxAttempts = 30,
            MaxCashWait = 120,
            Shuffle = false,
            ReserveSlots = 0,
            Units = {
                {name = "unit_cactus", pos = {103.56, -31.57, -62.66}},
                {name = "unit_cactus", pos = {106.36, -31.57, -65.83}},
                {name = "unit_cactus", pos = {104.14, -31.57, -59.03}},
                {name = "unit_palm_tree", pos = {122.24, -31.57, -62.39}},
                {name = "unit_cactus", pos = {106.53, -31.57, -62.49}},
                {name = "unit_cactus", pos = {103.92, -31.57, -56.04}},
                {name = "unit_cactus", pos = {106.19, -31.57, -58.65}},
            },
        },
        {
            Type = "WaitWave",
            Wave = 9,
        },
        {
            Type = "StartPlace",
            Name = "Place2_Palm_8to11",
            HardCap = 11,
            MaxCount = 4,
            SoftFail = false,
            MaxAttempts = 25,
            MaxCashWait = 90,
            Shuffle = false,
            ReserveSlots = 0,
            PauseUpgrade = true,
            Units = {
                {name = "unit_palm_tree", pos = {122.31, -31.57, -60.83}},
                {name = "unit_palm_tree", pos = {123.20, -31.57, -59.47}},
                {name = "unit_palm_tree", pos = {123.81, -31.57, -62.27}},
                {name = "unit_palm_tree", pos = {124.92, -31.57, -60.13}},
            },
        },
        {
            Type = "StartUpgradeAll",
            Name = "Upgrade_To15",
            RequireMinPlaced = 1,
            StopAtWave = 15,
        },
        {
            Type = "WaitWave",
            Wave = 15,
        },
        {
            Type = "StartPlace",
            Name = "Place3_Flower_12to15",
            HardCap = 15,
            MaxCount = 4,
            SoftFail = false,
            MaxAttempts = 25,
            MaxCashWait = 120,
            Shuffle = false,
            ReserveSlots = 0,
            PauseUpgrade = true,
            Units = {
                {name = "unit_scent_flower", pos = {131.84, -31.57, -57.48}},
                {name = "unit_scent_flower", pos = {134.01, -31.57, -60.08}},
                {name = "unit_scent_flower", pos = {134.40, -31.57, -55.74}},
                {name = "unit_scent_flower", pos = {136.38, -31.57, -58.37}},
            },
        },
        {
            Type = "StartUpgradeAll",
            Name = "Upgrade_To21",
            RequireMinPlaced = 1,
            StopAtWave = 21,
        },
        {
            Type = "WaitWave",
            Wave = 21,
        },
        {
            Type = "StartPlace",
            Name = "Place4_UFO_16to20",
            HardCap = 20,
            MaxCount = 5,
            SoftFail = false,
            MaxAttempts = 30,
            MaxCashWait = 120,
            Shuffle = false,
            ReserveSlots = 0,
            PauseUpgrade = true,
            Units = {
                {name = "unit_ufo", pos = {153.75, -26.75, -13.95}},
                {name = "unit_ufo", pos = {153.06, -26.75, -11.10}},
                {name = "unit_ufo", pos = {156.23, -26.75, -6.12}},
                {name = "unit_ufo", pos = {158.12, -26.75, -8.06}},
                {name = "unit_ufo", pos = {159.61, -26.75, -9.20}},
            },
        },
        {
            Type = "StartUpgradeAll",
            Name = "Upgrade_End",
            RequireMinPlaced = 0,
            UntilGameEnd = true,
        },
    },
}
