return {
    Name = "Volcano ( Medium )",
    Difficulty = "dif_normal",
    MaxPlace = 20,
    UfoReserve = 1,
    DefaultAngle = {-math.pi, 0, -math.pi},
    DefaultRotation = 180,
    Price = {
        unit_cactus = 150,
        unit_palm_tree = 500,
        unit_ufo = 1200,
    },
    Events = {
        {
            Type = "StartUpgradeAll",
            Name = "UpgradeAll_Main",
            RequireMinPlaced = 1,
            StopAtWave = 15,
        },
        {
            Type = "StartPlace",
            Name = "Place1",
            HardCap = 13,
            MaxCount = 13,
            SoftFail = false,
            MaxAttempts = 25,
            MaxCashWait = 120,
            Shuffle = false,
            ReserveSlots = 1,
            Units = {
                {name = "unit_cactus", pos = {105.05, -31.57, -64.05}},
                {name = "unit_cactus", pos = {107.09, -31.57, -66.57}},
                {name = "unit_cactus", pos = {103.15, -31.57, -60.59}},
                {name = "unit_palm_tree", pos = {124.23, -31.57, -58.82}},
                {name = "unit_cactus", pos = {106.73, -31.57, -61.86}},
                {name = "unit_cactus", pos = {109.04, -31.57, -66.05}},
                {name = "unit_cactus", pos = {109.30, -31.57, -63.05}},
                {name = "unit_cactus", pos = {107.04, -31.57, -58.06}},
                {name = "unit_cactus", pos = {104.39, -31.57, -56.43}},
                {name = "unit_palm_tree", pos = {125.65, -31.57, -59.04}},
                {name = "unit_palm_tree", pos = {126.80, -31.57, -57.65}},
                {name = "unit_palm_tree", pos = {127.77, -31.57, -58.88}},
                {name = "unit_palm_tree", pos = {128.51, -31.57, -56.86}},
            },
        },
        {
            Type = "WaitWave",
            Wave = 15,
        },
        {
            Type = "StartPlace",
            Name = "Place2",
            HardCap = 19,
            MaxCount = 6,
            SoftFail = true,
            MaxAttempts = 5,
            MaxCashWait = 12,
            Shuffle = false,
            ReserveSlots = 1,
            PauseUpgrade = true,
            Units = {
                {name = "unit_cactus", pos = {150.51, -31.57, -47.59}},
                {name = "unit_cactus", pos = {148.95, -31.57, -49.34}},
                {name = "unit_cactus", pos = {152.19, -31.57, -45.30}},
                {name = "unit_cactus", pos = {153.22, -31.57, -43.67}},
                {name = "unit_cactus", pos = {146.99, -31.57, -51.14}},
                {name = "unit_cactus", pos = {145.11, -31.57, -52.78}, chance = 0.5},
            },
        },
        {
            Type = "StartUpgradeAll",
            Name = "UpgradeAll_AfterPlace2",
            RequireMinPlaced = 1,
            StopAtWave = 19,
        },
        {
            Type = "WaitWave",
            Wave = 19,
        },
        {
            Type = "StartPlace",
            Name = "Place3_UFO",
            HardCap = 20,
            MaxCount = 1,
            SoftFail = true,
            MaxAttempts = 30,
            MaxCashWait = 90,
            Shuffle = false,
            ReserveSlots = 0,
            PauseUpgrade = true,
            Units = {
                {name = "unit_ufo", pos = {150.64, -27.28, -38.52}},
            },
        },
        {
            Type = "StartUpgradeAll",
            Name = "UpgradeAll_End",
            RequireMinPlaced = 0,
            UntilGameEnd = true,
        },
    },
}
